apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: webapplications.example.com
spec:
  group: example.com
  names:
    kind: WebApplication
    plural: webapplications
  versions:
  - name: v1
    served: true
    referenceable: true
