apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: webapplication-composition
spec:
  compositeTypeRef:
    apiVersion: example.com/v1
    kind: WebApplication
  resources:
    - name: Deployment
      base:
        apiVersion: apps/v1
        kind: Deployment
        spec:
          replicas: spec.replicas
          template:
            spec:
              containers:
                - name: app
                  image: spec.image
    - name: Service
      base:
        apiVersion: v1
        kind: Service
        spec:
          selector:
            app: app
          ports:
            - protocol: TCP
              port: 8080
